services:
  - type: web
    name: wind-data-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: ENVIRONMENT
        value: production
