services:
  - type: web
    name: wind-data-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: python -m uvicorn main:app --reload --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
